In [14]:
import pandas as pd
from PIL import Image
import pandas as pd
import os
from sklearn.model_selection import train_test_split
import torchvision.models as models


# data preparation:do not need to run the below codes 

In [23]:
# Load the dataset
data = pd.read_csv('Bookshelves_5_labeled_df.csv', encoding='ISO-8859-1')


In [21]:
data

txt  confidence                                           vertices  \
0    Don't         100  [(1039, 566), (1066, 563), (1067, 576), (1040,...   
1      Lik         100  [(1066, 563), (1080, 561), (1081, 574), (1067,...   
2      AND         100  [(1112, 307), (1172, 309), (1170, 364), (1110,...   
3     FALL         100  [(1119, 346), (1187, 353), (1185, 373), (1117,...   
4     LOVE         100  [(1119, 502), (1183, 508), (1181, 530), (1117,...   
..     ...         ...                                                ...   
650    the         100  [(1039, 286), (1034, 324), (1007, 320), (1012,...   
651   from         100  [(1048, 219), (1040, 281), (1013, 277), (1021,...   
652   Half         100  [(1056, 159), (1049, 218), (1021, 214), (1028,...   
653    One         100  [(1063, 103), (1056, 155), (1029, 151), (1035,...   
654  RINGS         100  [(1422, 158), (1491, 154), (1492, 174), (1423,...   

                                              boundBox  \
0    {'Width': 28, 'Height': 16, 'Left': 1039, 'Top...   
1    {'Width': 15, 'Height': 15, 'Left': 1066, 'Top...   
2    {'Width': 62, 'Height': 57, 'Left': 1110, 'Top...   
3    {'Width': 70, 'Height': 27, 'Left': 1117, 'Top...   
4    {'Width': 66, 'Height': 28, 'Left': 1117, 'Top...   
..                                                 ...   
650  {'Width': 32, 'Height': 41, 'Left': 1007, 'Top...   
651  {'Width': 35, 'Height': 65, 'Left': 1013, 'Top...   
652  {'Width': 35, 'Height': 63, 'Left': 1021, 'Top...   
653  {'Width': 34, 'Height': 56, 'Left': 1029, 'Top...   
654  {'Width': 70, 'Height': 24, 'Left': 1422, 'Top...   

                             slopes       font   word_len   direction  \
0      (0.111, -13.0, 0.111, -13.0)  13.038405  27.166155  horizontal   
1      (0.143, -13.0, 0.143, -13.0)  13.038405  14.142136  horizontal   
2      (-0.033, 27.5, -0.033, 27.5)  55.036352  60.033324  horizontal   
3      (-0.103, 10.0, -0.088, 10.5)  20.597387  68.311769  horizontal   
4      (-0.094, 11.0, -0.094, 11.0)  22.090722  64.280635  horizontal   
..                              ...        ...        ...         ...   
650      (7.6, -0.148, 7.4, -0.111)  27.230422  37.831923    vertical   
651   (7.75, -0.148, 7.625, -0.111)  27.230422  62.018176    vertical   
652  (8.429, -0.143, 8.429, -0.143)  28.284271  59.413803    vertical   
653  (7.429, -0.148, 8.667, -0.143)  27.789480  52.407024    vertical   
654    (0.058, -20.0, 0.058, -20.0)  20.024984  69.115845  horizontal   

         center_point crop_idx  Left  Top  Label  
0     (1053.0, 571.0)   (0, 0)  1039  563      0  
1     (1073.5, 568.5)   (0, 0)  1066  561      0  
2     (1141.0, 335.5)   (0, 0)  1110  307      0  
3    (1152.0, 359.75)   (0, 0)  1117  346      0  
4     (1150.0, 516.0)   (0, 0)  1117  502      0  
..                ...      ...   ...  ...    ...  
650  (1023.0, 303.25)   (2, 1)  1007  283      1  
651  (1030.5, 248.25)   (2, 1)  1013  216      1  
652   (1038.5, 186.5)   (2, 1)  1021  155      1  
653  (1045.75, 127.0)   (2, 1)  1029   99      1  
654   (1457.0, 166.0)   (2, 1)  1422  154      1  

[655 rows x 13 columns]

In [2]:
import chardet
import pandas as pd
from ActivePyTools.grab_data import eval_object_columns

def grab_df_data(df_path):
    with open(df_path, 'rb') as file:
        encoding = chardet.detect(file.read())['encoding']

    temp_df = pd.read_csv(df_path, encoding=encoding)
    df = eval_object_columns(temp_df)
    return df

split_df = grab_df_data('../data/split_df.csv')
split_df

txt                                           vertices  \
0               ARM  [(2942, 1224), (2980, 1228), (2979, 1239), (29...   
1             808.3  [(464, 1188), (525, 1190), (525, 1203), (464, ...   
2     UNPREDICTABLE  [(2464, 807), (2459, 942), (2445, 941), (2450,...   
3             TRUTH   [(679, 381), (680, 456), (662, 456), (661, 381)]   
4             808.3  [(706, 1177), (767, 1180), (766, 1201), (705, ...   
...             ...                                                ...   
1884            the   [(524, 284), (508, 302), (499, 294), (515, 276)]   
1885      Kamkwanba     [(370, 98), (370, 162), (360, 162), (360, 98)]   
1886             AN  [(2465, 777), (2464, 800), (2450, 799), (2451,...   
1887            MUS  [(3236, 1232), (3274, 1235), (3273, 1247), (32...   
1888            AND  [(1002, 348), (1004, 374), (994, 375), (992, 3...   

                                               boundBox  \
0     {'Width': 39, 'Height': 15, 'Left': 2941, 'Top...   
1     {'Width': 61, 'Height': 15, 'Left': 464, 'Top'...   
2     {'Width': 19, 'Height': 135, 'Left': 2445, 'To...   
3     {'Width': 19, 'Height': 75, 'Left': 661, 'Top'...   
4     {'Width': 62, 'Height': 24, 'Left': 705, 'Top'...   
...                                                 ...   
1884  {'Width': 25, 'Height': 26, 'Left': 499, 'Top'...   
1885  {'Width': 10, 'Height': 64, 'Left': 360, 'Top'...   
1886  {'Width': 15, 'Height': 23, 'Left': 2450, 'Top...   
1887  {'Width': 39, 'Height': 15, 'Left': 3235, 'Top...   
1888  {'Width': 12, 'Height': 27, 'Left': 992, 'Top'...   

                                slopes       font    word_len   direction  \
0         (-0.105, 11.0, -0.105, 11.0)  11.045361   38.209946  horizontal   
1     (-0.033, 1000.0, -0.033, 1000.0)  13.000000   61.032778  horizontal   
2           (27.0, -0.071, 26.8, -0.0)  14.017834  134.592906    vertical   
3            (-75.0, 0.0, -75.0, -0.0)  18.000000   75.006666    vertical   
4         (-0.049, 21.0, -0.049, 21.0)  21.023796   61.073726  horizontal   
...                                ...        ...         ...         ...   
1884    (1.125, -0.889, 1.125, -0.889)  12.041595   24.083189    vertical   
1885       (1000.0, 0.0, 1000.0, -0.0)  10.000000   64.000000    vertical   
1886        (23.0, -0.071, 22.0, -0.0)  14.017834   22.522222    vertical   
1887      (-0.079, 12.0, -0.079, 12.0)  12.041595   38.118237  horizontal   
1888          (-13.0, 0.1, -13.0, 0.1)  10.049876   26.076810    vertical   

          center_point  Label  \
0     (2960.5, 1231.5)      0   
1      (494.5, 1195.5)      0   
2     (2454.5, 874.25)      1   
3       (670.5, 418.5)      1   
4      (736.0, 1189.0)      0   
...                ...    ...   
1884    (511.5, 289.0)      1   
1885    (365.0, 130.0)      1   
1886  (2457.5, 788.25)      1   
1887  (3254.5, 1239.5)      0   
1888    (998.0, 361.5)      1   

                                               img_path   idx   type  \
0         ./docs/crop_pics/google/IMG_7940.jpeg_0_0.jpg  1325  train   
1         ./docs/crop_pics/google/IMG_7940.jpeg_0_0.jpg  1024  train   
2         ./docs/crop_pics/google/IMG_7940.jpeg_0_0.jpg  1274  train   
3     ./docs/crop_pics/google/Bookshelves_4.jpg_1_0.jpg   660  train   
4         ./docs/crop_pics/google/IMG_7940.jpeg_0_0.jpg  1054  train   
...                                                 ...   ...    ...   
1884  ./docs/crop_pics/google/Bookshelves_4.jpg_3_1.jpg   967  valid   
1885  ./docs/crop_pics/google/Bookshelves_4.jpg_3_0.jpg   856  valid   
1886      ./docs/crop_pics/google/IMG_7940.jpeg_0_0.jpg  1275  valid   
1887      ./docs/crop_pics/google/IMG_7940.jpeg_0_0.jpg  1344  valid   
1888  ./docs/crop_pics/google/Bookshelves_1.jpg_1_0.jpg   359  valid   

                            crop_path  
0        cropped_images/cropped_0.jpg  
1        cropped_images/cropped_1.jpg  
2        cropped_images/cropped_2.jpg  
3        cropped_images/cropped_3.jpg  
4        cropped_images/cropped

In [52]:
def crop_image_from_vertices(image_path, vertices, expand=10):
    """
    Crop image based on vertices with expansion.
    Arguments:
    - image_path: str, path to the image file
    - vertices: list of tuples, each tuple is a coordinate (x, y)
    - expand: int, number of pixels to expand the crop area
    """
    img = Image.open(image_path)
    min_x = min([v[0] for v in vertices])
    min_y = min([v[1] for v in vertices])
    max_x = max([v[0] for v in vertices])
    max_y = max([v[1] for v in vertices])
    
    # Expand the box by 'expand' pixels
    min_x = max(0, min_x - expand)
    min_y = max(0, min_y - expand)
    max_x = min(img.width, max_x + expand)
    max_y = min(img.height, max_y + expand)
    
    cropped_image = img.crop((min_x, min_y, max_x, max_y))
    return cropped_image


In [59]:
split_df_copy = split_df.copy()

for index, row in split_df_copy.iterrows():
    path = '../' + row.img_path
    vertices = row.vertices
    cropped_image = crop_image_from_vertices(path, vertices, expand=20)  # You can adjust the expansion here
    crop_path = f'cropped_images/cropped_{index}.jpg'
    cropped_image.save(crop_path)  # Save each cropped image
    split_df.loc[index, 'crop_path'] = crop_path

In [88]:
split_df.to_csv('../data/split_df.csv', index=False, encoding='utf-8')

In [3]:
import torch
print(torch.__version__)


2.2.1


# Start running codes from here

In [4]:
import torch
import torchvision.models as models
from torchvision import transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image
import pandas as pd
from sklearn.model_selection import train_test_split

model = models.resnet50(pretrained=True)

for param in model.parameters():
    param.requires_grad = False

num_ftrs = model.fc.in_features
model.fc = torch.nn.Linear(num_ftrs, 2)

D:\Anaconda3\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\Anaconda3\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [7]:
train_df = split_df[split_df['type'] == 'train']
valid_df = split_df[split_df['type'] == 'valid']
test_df = split_df[split_df['type'] == 'test']

In [6]:
import os
print(os.getcwd())

D:\GitHub\XN\cnn_model


In [32]:
class BookshelfDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.dataframe = dataframe
        self.transform = transform

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        img_path = self.dataframe.iloc[idx]['crop_path']  # Assuming image path is last column
        image = Image.open(img_path).convert('RGB')
        label = int(self.dataframe.iloc[idx]['Label'])

        if self.transform:
            image = self.transform(image)

        return image, label

# Transforms for the input data
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

train_dataset = BookshelfDataset(train_df, transform=transform)
valid_dataset = BookshelfDataset(valid_df, transform=transform)
test_dataset = BookshelfDataset(test_df, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
valid_loader = DataLoader(valid_dataset, batch_size=64, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

In [33]:
print(f"Training data size: {train_df.shape}")
print(f"Validation data size: {valid_df.shape}")
print(f"Test data size: {test_df.shape}")


Training data size: (1320, 13)
Validation data size: (284, 13)
Test data size: (285, 13)


In [44]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
criterion = torch.nn.CrossEntropyLoss()

In [45]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

def apply_metric(y_actual, preds, enable_print=True):

    cm = confusion_matrix(y_actual, preds)
    TN = cm[0, 0]
    FP = cm[0, 1]

    precision = precision_score(y_actual, preds, zero_division=0)
    recall = recall_score(y_actual, preds)
    specificity = TN / (TN + FP)
    accuracy = accuracy_score(y_actual, preds)

    if enable_print:
        print(f"CM: \n{cm}")
        print(f'Precision: {precision:.2f}')
        print(f'Recall: {recall:.2f}')
        print(f'Specificity: {specificity:.2f}')
        print(f'Accuracy: {accuracy:.2f}')

    return precision, recall, specificity, cm

In [46]:
def evaluate_model(model, loader):
    model.eval()  # Set the model to evaluation mode
    correct = 0
    total = 0
    predicts = []
    label_lst = []
    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            predicts.extend(predicted.cpu().numpy())
            label_lst.extend(labels.cpu().numpy())
    
    accuracy = 100 * correct / total
    return accuracy, predicts, label_lst


In [51]:
learn_rate = 0.0001
optimizer = torch.optim.Adam(model.fc.parameters(), lr=learn_rate)  # 只优化新的全连接层

def train_model(model, train_loader, valid_loader, num_epochs=50, lr=0.0001):
    best_accuracy = 0
    last_loss = 0
    
    for epoch in range(num_epochs):
        model.train()
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
        
        if (epoch + 1) % 10 == 0:
            accuracy, predicts, label_lst = evaluate_model(model, valid_loader)
            apply_metric(label_lst, predicts)
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}, Accuracy: {accuracy}%')
            if last_loss != 0:
                if loss.item() > last_loss:
                    lr /= 2
                    for param_group in optimizer.param_groups:
                        param_group['lr'] = lr
            last_loss = loss.item()
            
            # Save the model if the accuracy is the best
            if accuracy > best_accuracy:
                best_accuracy = accuracy
                torch.save(model.state_dict(), f'model_epoch_{epoch+1}.pth')
                print(f"Best model saved with accuracy: {accuracy}%")


In [43]:
train_model(model, train_loader, valid_loader, num_epochs=100)

CM: 
[[ 38  26]
 [ 35 185]]
Precision: 0.88
Recall: 0.84
Specificity: 0.59
Accuracy: 0.79
Epoch [10/100], Loss: 0.2559574246406555, Accuracy: 78.52112676056338%
Best model saved with accuracy: 78.52112676056338%
CM: 
[[ 37  27]
 [ 33 187]]
Precision: 0.87
Recall: 0.85
Specificity: 0.58
Accuracy: 0.79
Epoch [20/100], Loss: 0.27055805921554565, Accuracy: 78.87323943661971%
Best model saved with accuracy: 78.87323943661971%
CM: 
[[ 39  25]
 [ 33 187]]
Precision: 0.88
Recall: 0.85
Specificity: 0.61
Accuracy: 0.80
Epoch [30/100], Loss: 0.27194634079933167, Accuracy: 79.5774647887324%
Best model saved with accuracy: 79.5774647887324%
CM: 
[[ 37  27]
 [ 27 193]]
Precision: 0.88
Recall: 0.88
Specificity: 0.58
Accuracy: 0.81
Epoch [40/100], Loss: 0.23584172129631042, Accuracy: 80.98591549295774%
Best model saved with accuracy: 80.98591549295774%
CM: 
[[ 37  27]
 [ 29 191]]
Precision: 0.88
Recall: 0.87
Specificity: 0.58
Accuracy: 0.80
Epoch [50/100], Loss: 0.28420206904411316, Accuracy: 80.28169

In [52]:
train_model(model, train_loader, valid_loader, num_epochs=200)

CM: 
[[ 41  23]
 [ 35 185]]
Precision: 0.89
Recall: 0.84
Specificity: 0.64
Accuracy: 0.80
Epoch [10/200], Loss: 0.1498676836490631, Accuracy: 79.5774647887324%
Best model saved with accuracy: 79.5774647887324%
CM: 
[[ 39  25]
 [ 31 189]]
Precision: 0.88
Recall: 0.86
Specificity: 0.61
Accuracy: 0.80
Epoch [20/200], Loss: 0.2574372887611389, Accuracy: 80.28169014084507%
Best model saved with accuracy: 80.28169014084507%
CM: 
[[ 41  23]
 [ 36 184]]
Precision: 0.89
Recall: 0.84
Specificity: 0.64
Accuracy: 0.79
Epoch [30/200], Loss: 0.1372232437133789, Accuracy: 79.22535211267606%
CM: 
[[ 40  24]
 [ 37 183]]
Precision: 0.88
Recall: 0.83
Specificity: 0.62
Accuracy: 0.79
Epoch [40/200], Loss: 0.21462222933769226, Accuracy: 78.52112676056338%
CM: 
[[ 41  23]
 [ 33 187]]
Precision: 0.89
Recall: 0.85
Specificity: 0.64
Accuracy: 0.80
Epoch [50/200], Loss: 0.20011842250823975, Accuracy: 80.28169014084507%
CM: 
[[ 40  24]
 [ 29 191]]
Precision: 0.89
Recall: 0.87
Specificity: 0.62
Accuracy: 0.81
Epo